%% Constraints

% Input constraitn matrix
Ic = [eye(4);-eye(4)];
Iu = kron(eye(dim.N),Ic);
I_const = repmat([param.m*param.g/4;...
                  param.m*param.g/4;...
                  param.m*param.g/4;...
                  param.m*param.g/4;...
                  param.m*param.g/4;...
                  param.m*param.g/4;...
                  param.m*param.g/4;...
                  param.m*param.g/4],dim.N,1);


%Output state constraint matrix
state_ub = [pi;pi/2;pi];
state_lb = [-pi;-pi/2;-pi];
state_constr = repmat([state_ub;-state_lb],dim.N,1);
Cz = [  0 0 0 1 0 0 0 0 0 0 0 0;...
        0 0 0 0 1 0 0 0 0 0 0 0;...
        0 0 0 0 0 1 0 0 0 0 0 0];
Cz = [Cz;-Cz];              
Cz = kron(eye(dim.N),Cz);
